FIGURE_STYLES = [
    'neo',
    'game_room',
    'wood',
    'glass',
    'gothic',
    'classic',
    'metal',
    'bases',
    'neo_wood',
    'icy_sea',
    'club',
    'ocean',
    'newspaper',
    'blindfold',
    'space',
    'cases',
    'condal',
    '3d_chesskid',
    '8_bit',
    'marble',
    'book',
    'alpha',
    'bubblegum',
    'dash',
    'graffiti',
    'light',
    'lolz',
    'luca',
    'maya',
    'modern',
    'nature',
    'neon',
    'sky',
    'tigers',
    'tournament',
    'vintage',
    '3d_staunton',
    '3d_wood',
    '3d_plastic'
]

BOARD_STYLES = [
    'green',
    'dark_wood',
    'glass',
    'brown',
    'icy_sea',
    'newspaper',
    'walnut',
    'sky',
    'lolz',
    'stone',
    'bases',
    '8_bit',
    'marble',
    'purple',
    'translucent',
    'metal',
    'tournament',
    'dash',
    'burled_wood',
    'blue',
    'bubblegum',
    'checkers',
    'graffiti',
    'light',
    'neon',
    'orange',
    'overlay',
    'parchment',
    'red',
    'sand',
    'tan'
]

BG_STYLES = [
    'game_room',
    'light',
    'wood',
    'glass',
    'tournament',
    'staunton',
    'newspaper',
    'tigers',
    'nature',
    'sky',
    'ocean',
    'metal',
    'gothic',
    'marble',
    'neon',
    'graffiti',
    'bubblegum',
    'lolz',
    'icy_sea',
]

FIGURES = [
    'br.png',
    'bn.png',
    'bb.png',
    'bq.png',
    'bk.png',
    'bp.png',
    'wr.png',
    'wn.png',
    'wb.png',
    'wq.png',
    'wk.png',
    'wp.png'
]

CLASS_NAMES_DICT = {
    'black-bishop': 0,
    'black-king': 1,
    'black-knight': 2,
    'black-pawn': 3,
    'black-queen': 4,
    'black-rook': 5,
    'white-bishop': 6,
    'white-king': 7,
    'white-knight': 8,
    'white-pawn': 9,
    'white-queen': 10,
    'white-rook': 11,
}

FIGURES_PATH = {
    0: ('black-bishop', 'bb.png'),
    1: ('black-king', 'bk.png'),
    2: ('black-knight', 'bn.png'),
    3: ('black-pawn', 'bp.png'),
    4: ('black-queen', 'bq.png'),
    5: ('black-rook', 'br.png'),
    6: ('white-bishop', 'wb.png'),
    7: ('white-king', 'wk.png'),
    8: ('white-knight', 'wn.png'),
    9: ('white-pawn', 'wp.png'),
    10: ('white-queen', 'wq.png'),
    11: ('white-rook', 'wr.png'),
}

